title: TaskLane
description: A Windows-style taskbar for macOS
url: https://bnjdpn.github.io
baseurl: /TaskLane
repository: bnjdpn/TaskLane

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
